export const SOCKET_EVENTS = {
  // Client -> Server
  JOIN_GAME: 'join-game',
  SELECT_TEAM: 'select-team',
  RENAME_TEAM: 'rename-team',
  UPDATE_SETTINGS: 'update-settings',
  START_GAME: 'start-game',
  MARK_WORD: 'mark-word',
  END_ROUND_EARLY: 'end-round-early',
  CONTINUE_NEXT_ROUND: 'continue-next-round',
  RESET_GAME: 'reset-game',
  REQUEST_QUIT_WARNINGS: 'request-quit-warnings',
  PLAYER_QUIT: 'player-quit',
  HOST_CLOSE_ACTIVITY: 'host-close-activity',
  CREATE_REMATCH: 'create-rematch',
  INITIATE_DISPUTE: 'initiate-dispute',
  CAST_DISPUTE_VOTE: 'cast-dispute-vote',
  CANCEL_DISPUTE: 'cancel-dispute',
  MARK_STEAL_WORD: 'mark-steal-word',

  // Server -> Client
  CONNECT: 'connect',
  PLAYER_JOINED: 'player-joined',
  GAME_STATE: 'game-state',
  ROUND_STARTED: 'round-started',
  TIMER_UPDATE: 'timer-update',
  ROUND_ENDED: 'round-ended',
  ERROR: 'error',
  QUIT_WARNINGS: 'quit-warnings',
  QUIT_CONFIRMATION_REQUIRED: 'quit-confirmation-required',
  QUIT_CONFIRMED: 'quit-confirmed',
  PLAYER_QUIT_EVENT: 'player-quit',
  CLOSE_ACTIVITY_CONFIRMATION_REQUIRED: 'close-activity-confirmation-required',
  ACTIVITY_CLOSED: 'activity-closed',
  REMATCH_CREATED: 'rematch-created',
  DISPUTE_STARTED: 'dispute-started',
  DISPUTE_VOTE_RECORDED: 'dispute-vote-recorded',
  DISPUTE_RESOLVED: 'dispute-resolved',
  DISPUTE_ERROR: 'dispute-error',
  LAST_WORD_STEAL_STARTED: 'last-word-steal-started',
  STEAL_TIMER_UPDATE: 'steal-timer-update',
} as const;

export type SocketEvent = typeof SOCKET_EVENTS[keyof typeof SOCKET_EVENTS];
